# Change these first
owner: erdav544 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: erdav544

sites:
  - name: Stirling PDF
    url: https://pdf.erdav.eu.org
    expectedStatusCode:
      - 403
  - name: TeleDrive
    url: https://teledrive.erdav.eu.org
  - name: Sun Pegasus
    check: "tcp-ping"
    url: $SUN_PEGASUS_IP
  - name: Twilight
    check: "tcp-ping"
    url: $TWILIGHT_IP

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.erdav.eu.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Erdav's Systems Status
  introTitle: "Welcome to Erdav's systems status page."
  introMessage: Below you'll find status information for each of Erdav's services in **real-time**.
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
